### ISSUE TITLE
Privacy settings changed, new default is true

### ISSUE THREAD

**Issue by Harry-W-Haines-III** [linuxmint/alpha-testing#24]
After updating to the alpha, there is a new setting in the dconf file:
[org/cinnamon/desktop/privacy]
remember-recent-files=true

So this requires the user to go into System Settings | Privacy and toggle "Remember recently accessed files" OFF

Is this the new default?

**Comment by JosephMcc** [comment]
Yes this is the new default. I don't believe it's a new setting though. It used to be this way and was changed due to some technical problems it caused. It's now back. Updating doesn't usually change these settings though.

**Comment by Harry-W-Haines-III** [comment]
If would seem most users would prefer it off as it has been for a while since Mint has a reputation for respecting privacy.

**Comment by JosephMcc** [comment]
Not so sure I agree. It disables other features like recent files in things like your text editor. People actually complained quite a bit when we disabled this originally. And we don't modify it on upgrade. Your setting was set at default and the new default is on.

**Comment by Harry-W-Haines-III** [comment]
Kate, for example, has its own method of tracking recently used files (which can be turned off).  I understand what you are saying.  But it seems there are better ways now to accomplish this at the Application level, rather than change a global setting that has been set off for a while.  No biggie, just wanted to bring it up.  I can change it with a script I run anyway.

**Comment by clefebvre** [comment]
Hi,

It's a GTK setting which is ON and has been ON everywhere else except for in recent Cinnamon editions. The reason we turned it OFF was because of a memory leak we couldn't identify properly but which we knew was related to recent documents (a part of cinnamon called docinfo). Docinfo was reviewed this cycle and this setting was turned ON again.

The setting module, which contains this setting is called PRIVACY, and so I can understand why you would be worried about something related to privacy being turned ON like that. That said, this is just Cinnamon going back to using recent documents again, like it did in the past, and like any other DE does beside it. It's also common practice on smartphones and software in general to remember your history and simply let you erase it easily.

**Comment by Harry-W-Haines-III** [comment]
Thank you for taking the time for a detailed explanation and the background of why it was changed back.
